### ISSUE TITLE
Title features

### ISSUE THREAD

**Issue by blink1073** [phosphorjs/phosphor-ui#1]
- Add a `tooltip` attribute that translates to a DOM `title`
- Add a context menu handler

**Comment by blink1073** [comment]
Use case for `tooltip`: display the full path to a file.
Use case for context menu: "show in file browser" -> opens the file browser, cd to folder, selects the file

**Comment by blink1073** [comment]
cf: https://github.com/jupyter/jupyter-js-notebook/issues/140

**Comment by sccolbert** [comment]
Is the context menu feature relevant to the `Title` class, or the separate widgets that consume titles? 

i.e. are you asking for a context menu callback added to the `Title` object?

**Comment by blink1073** [comment]
It could be a message passed to the widget itself with the context menu event.

**Comment by blink1073** [comment]
You'd have to have the event itself or at least the target node to know where to show the popup menu.

**Comment by sccolbert** [comment]
The tab bar only knows about the `Title`, not the widget. So it would either have to be a callback on the title object, or a signal on the tab bar.

**Comment by blink1073** [comment]
If it were a signal, it would have to propagate through the dock panel and the app shell in order to get a hold of it.  I'd vote for a callback on the title object.

**Comment by blink1073** [comment]
Moved to https://github.com/phosphorjs/phosphor/issues/104
